Repository SavandBros/savandbros, pull requests merged in 2018-07, with the labels that each got.

#25 Translation finishup
  config.json
  gulpfile.js
  i18n/en.yaml
  i18n/fa.yaml
  i18n/ru.yaml
  layouts/index.html
  package.json
  static/package.json
Labels: enhancement, translation

#24 Translation
  .editorconfig
  config.json
  config.toml
  gulpfile.js
  i18n/en.yaml
  i18n/fa.yaml
  i18n/ru.yaml
  layouts/index.html
  package.json
  static/package.json
Labels: enhancement, help wanted

#30 Language selection
  config.json
  gulpfile.js
  i18n/en.json
  i18n/en.yaml
  i18n/fa.json
  i18n/fa.yaml
  i18n/ru.json
  i18n/ru.yaml
  layouts/index.html
Labels: enhancement

#37 Sync Translations
  README.md
  package.json
  scripts/sync_trans.js
Labels: feature, improvement
